<?php

namespace AppBundle\Repository;

/**
 * CarPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
