<?php

namespace AppBundle\Repository;

/**
 * SectionPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
